/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UrunlerRouteImport } from './routes/urunler'
import { Route as TakvimRouteImport } from './routes/takvim'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SatisFaturalariRouteImport } from './routes/satis-faturalari'
import { Route as RaporlarRouteImport } from './routes/raporlar'
import { Route as MusterilerRouteImport } from './routes/musteriler'
import { Route as KullanicilarRouteImport } from './routes/kullanicilar'
import { Route as KasaRouteImport } from './routes/kasa'
import { Route as GiderlerRouteImport } from './routes/giderler'
import { Route as GelirlerRouteImport } from './routes/gelirler'
import { Route as FiyatTeklifiRouteImport } from './routes/fiyat-teklifi'
import { Route as FirmaAyarlariRouteImport } from './routes/firma-ayarlari'
import { Route as EFaturaEntegrasyonRouteImport } from './routes/e-fatura-entegrasyon'
import { Route as EArsivRouteImport } from './routes/e-arsiv'
import { Route as CariHesaplarRouteImport } from './routes/cari-hesaplar'
import { Route as BildirimlerRouteImport } from './routes/bildirimler'
import { Route as BankalarRouteImport } from './routes/bankalar'
import { Route as AlisFaturalariRouteImport } from './routes/alis-faturalari'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PazaryerleriTurkcellPasajRouteImport } from './routes/pazaryerleri.turkcell-pasaj'
import { Route as PazaryerleriTrendyolRouteImport } from './routes/pazaryerleri.trendyol'
import { Route as PazaryerleriPttavmRouteImport } from './routes/pazaryerleri.pttavm'
import { Route as PazaryerleriPazaramaRouteImport } from './routes/pazaryerleri.pazarama'
import { Route as PazaryerleriN11RouteImport } from './routes/pazaryerleri.n11'
import { Route as PazaryerleriIdefixRouteImport } from './routes/pazaryerleri.idefix'
import { Route as PazaryerleriHepsiburadaRouteImport } from './routes/pazaryerleri.hepsiburada'
import { Route as PazaryerleriCiceksepetiRouteImport } from './routes/pazaryerleri.ciceksepeti'
import { Route as PazaryerleriAyarlarRouteImport } from './routes/pazaryerleri.ayarlar'
import { Route as PazaryerleriAmazonRouteImport } from './routes/pazaryerleri.amazon'
import { Route as KasaIdRouteImport } from './routes/kasa.$id'
import { Route as BankalarHesaplarRouteImport } from './routes/bankalar.hesaplar'
import { Route as BankalarEkstrelerRouteImport } from './routes/bankalar.ekstreler'
import { Route as BankalarIdRouteImport } from './routes/bankalar.$id'
import { Route as ApiPublicHooksDriveBackupRouteImport } from './routes/api/public/hooks/drive-backup'

const UrunlerRoute = UrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => rootRouteImport,
} as any)
const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SatisFaturalariRoute = SatisFaturalariRouteImport.update({
  id: '/satis-faturalari',
  path: '/satis-faturalari',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporlarRoute = RaporlarRouteImport.update({
  id: '/raporlar',
  path: '/raporlar',
  getParentRoute: () => rootRouteImport,
} as any)
const MusterilerRoute = MusterilerRouteImport.update({
  id: '/musteriler',
  path: '/musteriler',
  getParentRoute: () => rootRouteImport,
} as any)
const KullanicilarRoute = KullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => rootRouteImport,
} as any)
const KasaRoute = KasaRouteImport.update({
  id: '/kasa',
  path: '/kasa',
  getParentRoute: () => rootRouteImport,
} as any)
const GiderlerRoute = GiderlerRouteImport.update({
  id: '/giderler',
  path: '/giderler',
  getParentRoute: () => rootRouteImport,
} as any)
const GelirlerRoute = GelirlerRouteImport.update({
  id: '/gelirler',
  path: '/gelirler',
  getParentRoute: () => rootRouteImport,
} as any)
const FiyatTeklifiRoute = FiyatTeklifiRouteImport.update({
  id: '/fiyat-teklifi',
  path: '/fiyat-teklifi',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmaAyarlariRoute = FirmaAyarlariRouteImport.update({
  id: '/firma-ayarlari',
  path: '/firma-ayarlari',
  getParentRoute: () => rootRouteImport,
} as any)
const EFaturaEntegrasyonRoute = EFaturaEntegrasyonRouteImport.update({
  id: '/e-fatura-entegrasyon',
  path: '/e-fatura-entegrasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const EArsivRoute = EArsivRouteImport.update({
  id: '/e-arsiv',
  path: '/e-arsiv',
  getParentRoute: () => rootRouteImport,
} as any)
const CariHesaplarRoute = CariHesaplarRouteImport.update({
  id: '/cari-hesaplar',
  path: '/cari-hesaplar',
  getParentRoute: () => rootRouteImport,
} as any)
const BildirimlerRoute = BildirimlerRouteImport.update({
  id: '/bildirimler',
  path: '/bildirimler',
  getParentRoute: () => rootRouteImport,
} as any)
const BankalarRoute = BankalarRouteImport.update({
  id: '/bankalar',
  path: '/bankalar',
  getParentRoute: () => rootRouteImport,
} as any)
const AlisFaturalariRoute = AlisFaturalariRouteImport.update({
  id: '/alis-faturalari',
  path: '/alis-faturalari',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriTurkcellPasajRoute =
  PazaryerleriTurkcellPasajRouteImport.update({
    id: '/pazaryerleri/turkcell-pasaj',
    path: '/pazaryerleri/turkcell-pasaj',
    getParentRoute: () => rootRouteImport,
  } as any)
const PazaryerleriTrendyolRoute = PazaryerleriTrendyolRouteImport.update({
  id: '/pazaryerleri/trendyol',
  path: '/pazaryerleri/trendyol',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriPttavmRoute = PazaryerleriPttavmRouteImport.update({
  id: '/pazaryerleri/pttavm',
  path: '/pazaryerleri/pttavm',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriPazaramaRoute = PazaryerleriPazaramaRouteImport.update({
  id: '/pazaryerleri/pazarama',
  path: '/pazaryerleri/pazarama',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriN11Route = PazaryerleriN11RouteImport.update({
  id: '/pazaryerleri/n11',
  path: '/pazaryerleri/n11',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriIdefixRoute = PazaryerleriIdefixRouteImport.update({
  id: '/pazaryerleri/idefix',
  path: '/pazaryerleri/idefix',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriHepsiburadaRoute = PazaryerleriHepsiburadaRouteImport.update({
  id: '/pazaryerleri/hepsiburada',
  path: '/pazaryerleri/hepsiburada',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriCiceksepetiRoute = PazaryerleriCiceksepetiRouteImport.update({
  id: '/pazaryerleri/ciceksepeti',
  path: '/pazaryerleri/ciceksepeti',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriAyarlarRoute = PazaryerleriAyarlarRouteImport.update({
  id: '/pazaryerleri/ayarlar',
  path: '/pazaryerleri/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const PazaryerleriAmazonRoute = PazaryerleriAmazonRouteImport.update({
  id: '/pazaryerleri/amazon',
  path: '/pazaryerleri/amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const KasaIdRoute = KasaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KasaRoute,
} as any)
const BankalarHesaplarRoute = BankalarHesaplarRouteImport.update({
  id: '/hesaplar',
  path: '/hesaplar',
  getParentRoute: () => BankalarRoute,
} as any)
const BankalarEkstrelerRoute = BankalarEkstrelerRouteImport.update({
  id: '/ekstreler',
  path: '/ekstreler',
  getParentRoute: () => BankalarRoute,
} as any)
const BankalarIdRoute = BankalarIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BankalarRoute,
} as any)
const ApiPublicHooksDriveBackupRoute =
  ApiPublicHooksDriveBackupRouteImport.update({
    id: '/api/public/hooks/drive-backup',
    path: '/api/public/hooks/drive-backup',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alis-faturalari': typeof AlisFaturalariRoute
  '/bankalar': typeof BankalarRouteWithChildren
  '/bildirimler': typeof BildirimlerRoute
  '/cari-hesaplar': typeof CariHesaplarRoute
  '/e-arsiv': typeof EArsivRoute
  '/e-fatura-entegrasyon': typeof EFaturaEntegrasyonRoute
  '/firma-ayarlari': typeof FirmaAyarlariRoute
  '/fiyat-teklifi': typeof FiyatTeklifiRoute
  '/gelirler': typeof GelirlerRoute
  '/giderler': typeof GiderlerRoute
  '/kasa': typeof KasaRouteWithChildren
  '/kullanicilar': typeof KullanicilarRoute
  '/musteriler': typeof MusterilerRoute
  '/raporlar': typeof RaporlarRoute
  '/satis-faturalari': typeof SatisFaturalariRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takvim': typeof TakvimRoute
  '/urunler': typeof UrunlerRoute
  '/bankalar/$id': typeof BankalarIdRoute
  '/bankalar/ekstreler': typeof BankalarEkstrelerRoute
  '/bankalar/hesaplar': typeof BankalarHesaplarRoute
  '/kasa/$id': typeof KasaIdRoute
  '/pazaryerleri/amazon': typeof PazaryerleriAmazonRoute
  '/pazaryerleri/ayarlar': typeof PazaryerleriAyarlarRoute
  '/pazaryerleri/ciceksepeti': typeof PazaryerleriCiceksepetiRoute
  '/pazaryerleri/hepsiburada': typeof PazaryerleriHepsiburadaRoute
  '/pazaryerleri/idefix': typeof PazaryerleriIdefixRoute
  '/pazaryerleri/n11': typeof PazaryerleriN11Route
  '/pazaryerleri/pazarama': typeof PazaryerleriPazaramaRoute
  '/pazaryerleri/pttavm': typeof PazaryerleriPttavmRoute
  '/pazaryerleri/trendyol': typeof PazaryerleriTrendyolRoute
  '/pazaryerleri/turkcell-pasaj': typeof PazaryerleriTurkcellPasajRoute
  '/api/public/hooks/drive-backup': typeof ApiPublicHooksDriveBackupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alis-faturalari': typeof AlisFaturalariRoute
  '/bankalar': typeof BankalarRouteWithChildren
  '/bildirimler': typeof BildirimlerRoute
  '/cari-hesaplar': typeof CariHesaplarRoute
  '/e-arsiv': typeof EArsivRoute
  '/e-fatura-entegrasyon': typeof EFaturaEntegrasyonRoute
  '/firma-ayarlari': typeof FirmaAyarlariRoute
  '/fiyat-teklifi': typeof FiyatTeklifiRoute
  '/gelirler': typeof GelirlerRoute
  '/giderler': typeof GiderlerRoute
  '/kasa': typeof KasaRouteWithChildren
  '/kullanicilar': typeof KullanicilarRoute
  '/musteriler': typeof MusterilerRoute
  '/raporlar': typeof RaporlarRoute
  '/satis-faturalari': typeof SatisFaturalariRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takvim': typeof TakvimRoute
  '/urunler': typeof UrunlerRoute
  '/bankalar/$id': typeof BankalarIdRoute
  '/bankalar/ekstreler': typeof BankalarEkstrelerRoute
  '/bankalar/hesaplar': typeof BankalarHesaplarRoute
  '/kasa/$id': typeof KasaIdRoute
  '/pazaryerleri/amazon': typeof PazaryerleriAmazonRoute
  '/pazaryerleri/ayarlar': typeof PazaryerleriAyarlarRoute
  '/pazaryerleri/ciceksepeti': typeof PazaryerleriCiceksepetiRoute
  '/pazaryerleri/hepsiburada': typeof PazaryerleriHepsiburadaRoute
  '/pazaryerleri/idefix': typeof PazaryerleriIdefixRoute
  '/pazaryerleri/n11': typeof PazaryerleriN11Route
  '/pazaryerleri/pazarama': typeof PazaryerleriPazaramaRoute
  '/pazaryerleri/pttavm': typeof PazaryerleriPttavmRoute
  '/pazaryerleri/trendyol': typeof PazaryerleriTrendyolRoute
  '/pazaryerleri/turkcell-pasaj': typeof PazaryerleriTurkcellPasajRoute
  '/api/public/hooks/drive-backup': typeof ApiPublicHooksDriveBackupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alis-faturalari': typeof AlisFaturalariRoute
  '/bankalar': typeof BankalarRouteWithChildren
  '/bildirimler': typeof BildirimlerRoute
  '/cari-hesaplar': typeof CariHesaplarRoute
  '/e-arsiv': typeof EArsivRoute
  '/e-fatura-entegrasyon': typeof EFaturaEntegrasyonRoute
  '/firma-ayarlari': typeof FirmaAyarlariRoute
  '/fiyat-teklifi': typeof FiyatTeklifiRoute
  '/gelirler': typeof GelirlerRoute
  '/giderler': typeof GiderlerRoute
  '/kasa': typeof KasaRouteWithChildren
  '/kullanicilar': typeof KullanicilarRoute
  '/musteriler': typeof MusterilerRoute
  '/raporlar': typeof RaporlarRoute
  '/satis-faturalari': typeof SatisFaturalariRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/takvim': typeof TakvimRoute
  '/urunler': typeof UrunlerRoute
  '/bankalar/$id': typeof BankalarIdRoute
  '/bankalar/ekstreler': typeof BankalarEkstrelerRoute
  '/bankalar/hesaplar': typeof BankalarHesaplarRoute
  '/kasa/$id': typeof KasaIdRoute
  '/pazaryerleri/amazon': typeof PazaryerleriAmazonRoute
  '/pazaryerleri/ayarlar': typeof PazaryerleriAyarlarRoute
  '/pazaryerleri/ciceksepeti': typeof PazaryerleriCiceksepetiRoute
  '/pazaryerleri/hepsiburada': typeof PazaryerleriHepsiburadaRoute
  '/pazaryerleri/idefix': typeof PazaryerleriIdefixRoute
  '/pazaryerleri/n11': typeof PazaryerleriN11Route
  '/pazaryerleri/pazarama': typeof PazaryerleriPazaramaRoute
  '/pazaryerleri/pttavm': typeof PazaryerleriPttavmRoute
  '/pazaryerleri/trendyol': typeof PazaryerleriTrendyolRoute
  '/pazaryerleri/turkcell-pasaj': typeof PazaryerleriTurkcellPasajRoute
  '/api/public/hooks/drive-backup': typeof ApiPublicHooksDriveBackupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alis-faturalari'
    | '/bankalar'
    | '/bildirimler'
    | '/cari-hesaplar'
    | '/e-arsiv'
    | '/e-fatura-entegrasyon'
    | '/firma-ayarlari'
    | '/fiyat-teklifi'
    | '/gelirler'
    | '/giderler'
    | '/kasa'
    | '/kullanicilar'
    | '/musteriler'
    | '/raporlar'
    | '/satis-faturalari'
    | '/sitemap.xml'
    | '/takvim'
    | '/urunler'
    | '/bankalar/$id'
    | '/bankalar/ekstreler'
    | '/bankalar/hesaplar'
    | '/kasa/$id'
    | '/pazaryerleri/amazon'
    | '/pazaryerleri/ayarlar'
    | '/pazaryerleri/ciceksepeti'
    | '/pazaryerleri/hepsiburada'
    | '/pazaryerleri/idefix'
    | '/pazaryerleri/n11'
    | '/pazaryerleri/pazarama'
    | '/pazaryerleri/pttavm'
    | '/pazaryerleri/trendyol'
    | '/pazaryerleri/turkcell-pasaj'
    | '/api/public/hooks/drive-backup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alis-faturalari'
    | '/bankalar'
    | '/bildirimler'
    | '/cari-hesaplar'
    | '/e-arsiv'
    | '/e-fatura-entegrasyon'
    | '/firma-ayarlari'
    | '/fiyat-teklifi'
    | '/gelirler'
    | '/giderler'
    | '/kasa'
    | '/kullanicilar'
    | '/musteriler'
    | '/raporlar'
    | '/satis-faturalari'
    | '/sitemap.xml'
    | '/takvim'
    | '/urunler'
    | '/bankalar/$id'
    | '/bankalar/ekstreler'
    | '/bankalar/hesaplar'
    | '/kasa/$id'
    | '/pazaryerleri/amazon'
    | '/pazaryerleri/ayarlar'
    | '/pazaryerleri/ciceksepeti'
    | '/pazaryerleri/hepsiburada'
    | '/pazaryerleri/idefix'
    | '/pazaryerleri/n11'
    | '/pazaryerleri/pazarama'
    | '/pazaryerleri/pttavm'
    | '/pazaryerleri/trendyol'
    | '/pazaryerleri/turkcell-pasaj'
    | '/api/public/hooks/drive-backup'
  id:
    | '__root__'
    | '/'
    | '/alis-faturalari'
    | '/bankalar'
    | '/bildirimler'
    | '/cari-hesaplar'
    | '/e-arsiv'
    | '/e-fatura-entegrasyon'
    | '/firma-ayarlari'
    | '/fiyat-teklifi'
    | '/gelirler'
    | '/giderler'
    | '/kasa'
    | '/kullanicilar'
    | '/musteriler'
    | '/raporlar'
    | '/satis-faturalari'
    | '/sitemap.xml'
    | '/takvim'
    | '/urunler'
    | '/bankalar/$id'
    | '/bankalar/ekstreler'
    | '/bankalar/hesaplar'
    | '/kasa/$id'
    | '/pazaryerleri/amazon'
    | '/pazaryerleri/ayarlar'
    | '/pazaryerleri/ciceksepeti'
    | '/pazaryerleri/hepsiburada'
    | '/pazaryerleri/idefix'
    | '/pazaryerleri/n11'
    | '/pazaryerleri/pazarama'
    | '/pazaryerleri/pttavm'
    | '/pazaryerleri/trendyol'
    | '/pazaryerleri/turkcell-pasaj'
    | '/api/public/hooks/drive-backup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlisFaturalariRoute: typeof AlisFaturalariRoute
  BankalarRoute: typeof BankalarRouteWithChildren
  BildirimlerRoute: typeof BildirimlerRoute
  CariHesaplarRoute: typeof CariHesaplarRoute
  EArsivRoute: typeof EArsivRoute
  EFaturaEntegrasyonRoute: typeof EFaturaEntegrasyonRoute
  FirmaAyarlariRoute: typeof FirmaAyarlariRoute
  FiyatTeklifiRoute: typeof FiyatTeklifiRoute
  GelirlerRoute: typeof GelirlerRoute
  GiderlerRoute: typeof GiderlerRoute
  KasaRoute: typeof KasaRouteWithChildren
  KullanicilarRoute: typeof KullanicilarRoute
  MusterilerRoute: typeof MusterilerRoute
  RaporlarRoute: typeof RaporlarRoute
  SatisFaturalariRoute: typeof SatisFaturalariRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TakvimRoute: typeof TakvimRoute
  UrunlerRoute: typeof UrunlerRoute
  PazaryerleriAmazonRoute: typeof PazaryerleriAmazonRoute
  PazaryerleriAyarlarRoute: typeof PazaryerleriAyarlarRoute
  PazaryerleriCiceksepetiRoute: typeof PazaryerleriCiceksepetiRoute
  PazaryerleriHepsiburadaRoute: typeof PazaryerleriHepsiburadaRoute
  PazaryerleriIdefixRoute: typeof PazaryerleriIdefixRoute
  PazaryerleriN11Route: typeof PazaryerleriN11Route
  PazaryerleriPazaramaRoute: typeof PazaryerleriPazaramaRoute
  PazaryerleriPttavmRoute: typeof PazaryerleriPttavmRoute
  PazaryerleriTrendyolRoute: typeof PazaryerleriTrendyolRoute
  PazaryerleriTurkcellPasajRoute: typeof PazaryerleriTurkcellPasajRoute
  ApiPublicHooksDriveBackupRoute: typeof ApiPublicHooksDriveBackupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/urunler': {
      id: '/urunler'
      path: '/urunler'
      fullPath: '/urunler'
      preLoaderRoute: typeof UrunlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satis-faturalari': {
      id: '/satis-faturalari'
      path: '/satis-faturalari'
      fullPath: '/satis-faturalari'
      preLoaderRoute: typeof SatisFaturalariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raporlar': {
      id: '/raporlar'
      path: '/raporlar'
      fullPath: '/raporlar'
      preLoaderRoute: typeof RaporlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musteriler': {
      id: '/musteriler'
      path: '/musteriler'
      fullPath: '/musteriler'
      preLoaderRoute: typeof MusterilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kullanicilar': {
      id: '/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/kullanicilar'
      preLoaderRoute: typeof KullanicilarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasa': {
      id: '/kasa'
      path: '/kasa'
      fullPath: '/kasa'
      preLoaderRoute: typeof KasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/giderler': {
      id: '/giderler'
      path: '/giderler'
      fullPath: '/giderler'
      preLoaderRoute: typeof GiderlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gelirler': {
      id: '/gelirler'
      path: '/gelirler'
      fullPath: '/gelirler'
      preLoaderRoute: typeof GelirlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiyat-teklifi': {
      id: '/fiyat-teklifi'
      path: '/fiyat-teklifi'
      fullPath: '/fiyat-teklifi'
      preLoaderRoute: typeof FiyatTeklifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firma-ayarlari': {
      id: '/firma-ayarlari'
      path: '/firma-ayarlari'
      fullPath: '/firma-ayarlari'
      preLoaderRoute: typeof FirmaAyarlariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-fatura-entegrasyon': {
      id: '/e-fatura-entegrasyon'
      path: '/e-fatura-entegrasyon'
      fullPath: '/e-fatura-entegrasyon'
      preLoaderRoute: typeof EFaturaEntegrasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-arsiv': {
      id: '/e-arsiv'
      path: '/e-arsiv'
      fullPath: '/e-arsiv'
      preLoaderRoute: typeof EArsivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cari-hesaplar': {
      id: '/cari-hesaplar'
      path: '/cari-hesaplar'
      fullPath: '/cari-hesaplar'
      preLoaderRoute: typeof CariHesaplarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bildirimler': {
      id: '/bildirimler'
      path: '/bildirimler'
      fullPath: '/bildirimler'
      preLoaderRoute: typeof BildirimlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bankalar': {
      id: '/bankalar'
      path: '/bankalar'
      fullPath: '/bankalar'
      preLoaderRoute: typeof BankalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alis-faturalari': {
      id: '/alis-faturalari'
      path: '/alis-faturalari'
      fullPath: '/alis-faturalari'
      preLoaderRoute: typeof AlisFaturalariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/turkcell-pasaj': {
      id: '/pazaryerleri/turkcell-pasaj'
      path: '/pazaryerleri/turkcell-pasaj'
      fullPath: '/pazaryerleri/turkcell-pasaj'
      preLoaderRoute: typeof PazaryerleriTurkcellPasajRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/trendyol': {
      id: '/pazaryerleri/trendyol'
      path: '/pazaryerleri/trendyol'
      fullPath: '/pazaryerleri/trendyol'
      preLoaderRoute: typeof PazaryerleriTrendyolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/pttavm': {
      id: '/pazaryerleri/pttavm'
      path: '/pazaryerleri/pttavm'
      fullPath: '/pazaryerleri/pttavm'
      preLoaderRoute: typeof PazaryerleriPttavmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/pazarama': {
      id: '/pazaryerleri/pazarama'
      path: '/pazaryerleri/pazarama'
      fullPath: '/pazaryerleri/pazarama'
      preLoaderRoute: typeof PazaryerleriPazaramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/n11': {
      id: '/pazaryerleri/n11'
      path: '/pazaryerleri/n11'
      fullPath: '/pazaryerleri/n11'
      preLoaderRoute: typeof PazaryerleriN11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/idefix': {
      id: '/pazaryerleri/idefix'
      path: '/pazaryerleri/idefix'
      fullPath: '/pazaryerleri/idefix'
      preLoaderRoute: typeof PazaryerleriIdefixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/hepsiburada': {
      id: '/pazaryerleri/hepsiburada'
      path: '/pazaryerleri/hepsiburada'
      fullPath: '/pazaryerleri/hepsiburada'
      preLoaderRoute: typeof PazaryerleriHepsiburadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/ciceksepeti': {
      id: '/pazaryerleri/ciceksepeti'
      path: '/pazaryerleri/ciceksepeti'
      fullPath: '/pazaryerleri/ciceksepeti'
      preLoaderRoute: typeof PazaryerleriCiceksepetiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/ayarlar': {
      id: '/pazaryerleri/ayarlar'
      path: '/pazaryerleri/ayarlar'
      fullPath: '/pazaryerleri/ayarlar'
      preLoaderRoute: typeof PazaryerleriAyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pazaryerleri/amazon': {
      id: '/pazaryerleri/amazon'
      path: '/pazaryerleri/amazon'
      fullPath: '/pazaryerleri/amazon'
      preLoaderRoute: typeof PazaryerleriAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kasa/$id': {
      id: '/kasa/$id'
      path: '/$id'
      fullPath: '/kasa/$id'
      preLoaderRoute: typeof KasaIdRouteImport
      parentRoute: typeof KasaRoute
    }
    '/bankalar/hesaplar': {
      id: '/bankalar/hesaplar'
      path: '/hesaplar'
      fullPath: '/bankalar/hesaplar'
      preLoaderRoute: typeof BankalarHesaplarRouteImport
      parentRoute: typeof BankalarRoute
    }
    '/bankalar/ekstreler': {
      id: '/bankalar/ekstreler'
      path: '/ekstreler'
      fullPath: '/bankalar/ekstreler'
      preLoaderRoute: typeof BankalarEkstrelerRouteImport
      parentRoute: typeof BankalarRoute
    }
    '/bankalar/$id': {
      id: '/bankalar/$id'
      path: '/$id'
      fullPath: '/bankalar/$id'
      preLoaderRoute: typeof BankalarIdRouteImport
      parentRoute: typeof BankalarRoute
    }
    '/api/public/hooks/drive-backup': {
      id: '/api/public/hooks/drive-backup'
      path: '/api/public/hooks/drive-backup'
      fullPath: '/api/public/hooks/drive-backup'
      preLoaderRoute: typeof ApiPublicHooksDriveBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BankalarRouteChildren {
  BankalarIdRoute: typeof BankalarIdRoute
  BankalarEkstrelerRoute: typeof BankalarEkstrelerRoute
  BankalarHesaplarRoute: typeof BankalarHesaplarRoute
}

const BankalarRouteChildren: BankalarRouteChildren = {
  BankalarIdRoute: BankalarIdRoute,
  BankalarEkstrelerRoute: BankalarEkstrelerRoute,
  BankalarHesaplarRoute: BankalarHesaplarRoute,
}

const BankalarRouteWithChildren = BankalarRoute._addFileChildren(
  BankalarRouteChildren,
)

interface KasaRouteChildren {
  KasaIdRoute: typeof KasaIdRoute
}

const KasaRouteChildren: KasaRouteChildren = {
  KasaIdRoute: KasaIdRoute,
}

const KasaRouteWithChildren = KasaRoute._addFileChildren(KasaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlisFaturalariRoute: AlisFaturalariRoute,
  BankalarRoute: BankalarRouteWithChildren,
  BildirimlerRoute: BildirimlerRoute,
  CariHesaplarRoute: CariHesaplarRoute,
  EArsivRoute: EArsivRoute,
  EFaturaEntegrasyonRoute: EFaturaEntegrasyonRoute,
  FirmaAyarlariRoute: FirmaAyarlariRoute,
  FiyatTeklifiRoute: FiyatTeklifiRoute,
  GelirlerRoute: GelirlerRoute,
  GiderlerRoute: GiderlerRoute,
  KasaRoute: KasaRouteWithChildren,
  KullanicilarRoute: KullanicilarRoute,
  MusterilerRoute: MusterilerRoute,
  RaporlarRoute: RaporlarRoute,
  SatisFaturalariRoute: SatisFaturalariRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TakvimRoute: TakvimRoute,
  UrunlerRoute: UrunlerRoute,
  PazaryerleriAmazonRoute: PazaryerleriAmazonRoute,
  PazaryerleriAyarlarRoute: PazaryerleriAyarlarRoute,
  PazaryerleriCiceksepetiRoute: PazaryerleriCiceksepetiRoute,
  PazaryerleriHepsiburadaRoute: PazaryerleriHepsiburadaRoute,
  PazaryerleriIdefixRoute: PazaryerleriIdefixRoute,
  PazaryerleriN11Route: PazaryerleriN11Route,
  PazaryerleriPazaramaRoute: PazaryerleriPazaramaRoute,
  PazaryerleriPttavmRoute: PazaryerleriPttavmRoute,
  PazaryerleriTrendyolRoute: PazaryerleriTrendyolRoute,
  PazaryerleriTurkcellPasajRoute: PazaryerleriTurkcellPasajRoute,
  ApiPublicHooksDriveBackupRoute: ApiPublicHooksDriveBackupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
